### ISSUE TITLE
How can I remedy memory leak of gnome-shell by uid: gdm

### ISSUE THREAD

**Issue by Alkaid-Benetnash** [adee/gnome-shell-aggressive-gc#1]
Thank you for this extension.
I can easily install it for my own gnome-shell. But there is also a gnome-shell owned by `gdm`, for which I have no idea how to install this extension.
For now, I can just regularly (approximately every 2 days) kill that process.

**Comment by dantrell** [comment]
Instead of using an extension embed it directly into GNOME Shell [like so](https://github.com/dantrell/gentoo-overlay-dantrell-gnome-3-28/blob/master/gnome-base/gnome-shell/files/gnome-shell-3.14.4-force-garbage-collection.patch)¹.

> **¹** This implementation cycles every 2 minutes. ↩
