### ISSUE TITLE
More recent versions of Gnome-shell?

### ISSUE THREAD

**Issue by Chris00** [adee/gnome-shell-aggressive-gc#2]
Is this extension supposed to work with more recent versions of Gnome-shell such as 42.4?  The [metadata only advertise 3.28](https://github.com/adee/gnome-shell-aggressive-gc/blob/master/forcegc%40email.com/metadata.json#L3).

**Comment by adee** [comment]
It is pointless to use this anymore. Gjs has now a more proper solution called "Big Hammer". The end result is pretty much the same, this one being much less efficient. 
I think I'll go ahead and archive this.
